### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by Jason-Cooke** [Jason-Cooke/Popular-Movies-Stage-1#1]
- [ ] Fetch data from themoviedb.org.
- [ ] Parse data
- [ ] Populate GridView with thumbnail images
- [ ] Create a new Activity for the details page
- [ ] Define and implement Settings.
